### ISSUE TITLE
Avoid interfaces prefix and classes suffix?

### ISSUE THREAD

**Issue by fooock** [Karumi/AndroidAudit#9]
I know that many developers use the prefix `I` for their interfaces, and the suffix `Impl` for their implementations, but isn't needed. I prefer to declare an interface like `DataRepository`, and create the default implementation class like `DefaultDataRepository`, Now, you can create a `MockDataRepository` class, and is perfectly readable without the class suffix. That's my point of view, small and concise.

It's also true that the code need to be readable for a stranger, and as a Java developers, maybe the `I` and `Impl` are the common case (like C# devs)... what is your opinion? You agree with me?

**Comment by pedrovgs** [comment]
Hi @fooock I'm really sorry but we don't use GitHub issues to give us our personal opinion about programing topics. We use GitHub issues as an issue tracker 😃  I'm closing this issue, sorry. Please if you want to know more about our thoughts feel free to send us an email.
